import type { Metadata } from "next";
import "./globals.css";
import { headerFont } from "./ui/fonts";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter"; // or `v13-appRouter` if you are using Next.js v13
import { ApolloWrapper } from "@/apolloProvider/clientProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${headerFont.className} antialiased`}>
        <AppRouterCacheProvider>
          <ApolloWrapper>{children}</ApolloWrapper>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
